//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.QueryServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cuttingedge.it/solid/queryservice/v1.0", ConfigurationName="QueryServices.QueryService")]
    public interface QueryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cuttingedge.it/solid/queryservice/v1.0/QueryService/Execute", ReplyAction="http://www.cuttingedge.it/solid/queryservice/v1.0/QueryService/ExecuteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Contract.Queries.Orders.GetOrderByIdQuery))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Contract.Queries.Orders.GetUnshippedOrdersForCurrentCustomerQuery))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Contract.DTOs.OrderInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Contract.DTOs.OrderInfo[]))]
        object Execute(object query);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QueryServiceChannel : Client.QueryServices.QueryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryServiceClient : System.ServiceModel.ClientBase<Client.QueryServices.QueryService>, Client.QueryServices.QueryService {
        
        public QueryServiceClient() {
        }
        
        public QueryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object Execute(object query) {
            return base.Channel.Execute(query);
        }
    }
}
