// <auto-generated />
#pragma warning disable 1591
namespace WcfService
{
    using System.ServiceModel;

    using Contract;
    using Contract.Queries.Orders;

    [ServiceContract(Namespace = "http://www.cuttingedge.it/solid/queryservice/v1.0")]
    public class NonDotNetQueryService
    {
        [OperationContract]
		[FaultContract(typeof(ValidationError))]
        public Contract.DTOs.OrderInfo GetOrderById(GetOrderByIdQuery query) => Execute(query);
			     
        [OperationContract]
		[FaultContract(typeof(ValidationError))]
        public Contract.Queries.Paged<Contract.DTOs.OrderInfo> GetUnshippedOrdersForCurrentCustomer(GetUnshippedOrdersForCurrentCustomerQuery query) => Execute(query);
			     
		private static TResult Execute<TResult>(IQuery<TResult> query) => (TResult)QueryService.ExecuteQuery(query);
	}
}
