//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.CommandServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.solid.net/commandservice/v1.0", ConfigurationName="CommandServices.CommandService")]
    public interface CommandService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.solid.net/commandservice/v1.0/CommandService/Execute", ReplyAction="http://www.solid.net/commandservice/v1.0/CommandService/ExecuteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Contract.Commands.Orders.CreateOrderCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Contract.Commands.Orders.ShipOrderCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Contract.DTOs.Address))]
        object Execute(object command);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CommandServiceChannel : Client.CommandServices.CommandService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommandServiceClient : System.ServiceModel.ClientBase<Client.CommandServices.CommandService>, Client.CommandServices.CommandService {
        
        public CommandServiceClient() {
        }
        
        public CommandServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommandServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommandServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommandServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object Execute(object command) {
            return base.Channel.Execute(command);
        }
    }
}
